from .core import BASE, SITE, UPDATED, breadcrumb, faq, page, quick_answer, takeaways


def build():
    path='/en/labs/agent-reliability/'
    target=SITE/'en/labs/agent-reliability'
    target.mkdir(parents=True,exist_ok=True)
    title='Agent Reliability Lab — Tune retries, limits, and guardrails | AhaFrame'
    desc='Tune a simulated customer-support agent by changing max steps, retries, timeouts, validation, human approval, and termination rules while watching success, runaway risk, safety, latency, and cost.'
    schema={
        '@context':'https://schema.org',
        '@graph':[
            {'@type':'WebPage','@id':BASE+path+'#webpage','url':BASE+path,'name':'Agent Reliability Lab','description':desc,'inLanguage':'en','dateModified':UPDATED,'mainEntity':{'@id':BASE+path+'#learning-resource'}},
            {'@type':'LearningResource','@id':BASE+path+'#learning-resource','name':'Agent Reliability Lab','description':desc,'url':BASE+path,'inLanguage':'en','educationalLevel':'Intermediate','learningResourceType':'Interactive simulation','timeRequired':'PT20M','isAccessibleForFree':True,'publisher':{'@id':BASE+'/#organization'}},
        ],
    }
    body=f'''<div class="container"><div class="breadcrumb"><a href="/en/">Home</a> / Production Labs / Agent Reliability Lab</div><section class="lesson-hero"><div class="lesson-title-row"><div class="lesson-icon">⌘</div><div><h1>Agent Reliability Lab</h1><div class="badges"><span class="badge level">Production Lab Preview</span><span class="badge">Intermediate</span><span class="badge">20 min</span></div><p class="lede">Start with an autonomous support agent that usually finishes the task—but retries too aggressively, can loop for too long, and may issue a refund without enough validation. Tune the control policy until reliability improves without hiding the cost and latency trade-offs.</p></div></div><div class="lesson-tools"><button type="button" class="btn small" data-share>Share</button></div></section>{quick_answer('Reliable agents are not agents that retry forever; they combine bounded execution, explicit validation, safe termination, and human control where irreversible actions justify it.')}
    <div data-agent-reliability-lab><section class="card interactive"><div class="panel-title"><span>Unreliable production scenario</span><span class="badge">Deterministic simulation</span></div><p class="subtle">Scenario: a customer-support agent looks up an account, checks refund policy, and may call an irreversible refund tool. The baseline has enough freedom to complete many tasks, but weak stopping rules and aggressive retries create reliability and safety debt.</p><div style="display:grid;grid-template-columns:1fr 1fr;gap:24px;margin-top:18px"><div><label class="label" for="agent-max-steps">Max steps</label><div class="control-row"><input id="agent-max-steps" class="slider" type="range" min="4" max="20" step="1" value="14"><output class="badge" data-agent-max-steps-value>14</output></div><label class="label" for="agent-retry-limit" style="display:block;margin-top:18px">Retry limit</label><div class="control-row"><input id="agent-retry-limit" class="slider" type="range" min="0" max="5" step="1" value="4"><output class="badge" data-agent-retry-value>4</output></div><label class="label" for="agent-timeout" style="display:block;margin-top:18px">Tool timeout</label><div class="control-row"><input id="agent-timeout" class="slider" type="range" min="2" max="20" step="1" value="12"><output class="badge" data-agent-timeout-value>12 s</output></div></div><div><label class="label" for="agent-termination">Termination rule</label><select id="agent-termination" class="select" style="margin-top:8px"><option value="weak">Weak: stop only at max steps</option><option value="bounded">Bounded: stop repeated failures</option><option value="goal-aware">Goal-aware: stop on success or repetition</option></select><button type="button" class="btn wide" data-agent-validation style="margin-top:16px">Result validation: OFF</button><button type="button" class="btn wide" data-agent-human style="margin-top:10px">Human approval: OFF</button><div class="note" style="margin-top:16px"><strong>Irreversible action:</strong> issuing a refund. Human approval therefore improves safety, but it also adds review load and latency.</div><div class="actions" style="margin-top:16px"><button type="button" class="btn primary" data-agent-balanced>Apply reliability preset</button><button type="button" class="btn" data-agent-reset>Reset unreliable baseline</button></div></div></div></section>
    <section class="card lesson-section" style="padding:20px;margin-top:18px"><div class="panel-title">What the system sees</div><div class="metrics" style="margin-top:14px"><div class="metric">Success rate<br><strong data-agent-success>—</strong></div><div class="metric">Reliability score<br><strong data-agent-reliability>—</strong></div><div class="metric">Runaway risk<br><strong data-agent-runaway>—</strong></div><div class="metric">Unsafe-action risk<br><strong data-agent-unsafe>—</strong></div><div class="metric">Sim latency<br><strong data-agent-latency>—</strong></div><div class="metric">Cost index<br><strong data-agent-cost>—</strong></div><div class="metric">Human reviews / 100<br><strong data-agent-reviews>—</strong></div></div><div class="note" style="margin-top:14px"><strong>Current diagnosis:</strong> <span data-agent-diagnosis>Calculating…</span></div><div class="compare-grid" style="margin-top:16px"><div class="compare-card warn"><span class="label">Unreliable baseline</span><strong>14 steps · 4 retries · weak termination</strong><p class="subtle">No result validation and no approval before an irreversible refund action.</p></div><span class="flow-arrow">→</span><div class="compare-card good"><span class="label">Your current policy</span><div data-agent-compare style="display:grid;gap:6px;margin-top:6px"><span>Waiting for changes…</span></div></div></div></section></div>
    {takeaways([('Retries are not free','Retries can recover transient failures, but aggressive retry budgets also increase execution length, latency, cost, and repeated-action risk.'),('Max steps are a safety boundary','A larger step budget can rescue complex tasks, but it also gives a confused agent more room to loop.'),('Validation changes correctness','Checking a tool result or proposed final action can catch bad state before it propagates into another step.'),('Human approval belongs at consequence boundaries','Approval is most valuable around irreversible or high-impact actions, where extra latency can be an acceptable trade for lower safety risk.'),('Termination is part of the agent design','Stopping on success, repeated failures, or repeated state is more reliable than treating max-steps exhaustion as the only exit.')])}
    <section class="card section-explainer"><span class="eyebrow">Production mental model</span><h2>Why do agents fail even when every tool works?</h2><p>An agent can have a capable model and functioning tools and still be unreliable. Reliability depends on the policy that connects observations to the next action: how long the loop may run, what gets retried, what must be validated, which actions require approval, and what counts as a legitimate stopping condition.</p><h3>More retries improve recovery—and expand the failure surface</h3><p>Transient tool errors justify retries, but retrying without a bounded policy can repeat side effects, amplify bad assumptions, and consume extra model/tool calls. Production agents should distinguish retryable failures from validation failures and permanent errors.</p><h3>Max steps are a guardrail, not a planning strategy</h3><p>A maximum step count is useful as a final circuit breaker, but it should not be the only termination rule. A good runtime can also stop when the goal is satisfied, the same failed state repeats, required information is unavailable, or the action budget no longer justifies another attempt.</p><h3>Validation and approval solve different problems</h3><p>Validation checks whether an observation, structured result, or proposed action is internally acceptable. Human approval introduces an external decision maker before a consequential action. Validation can run on every step; approval should be targeted where the consequence warrants the interruption.</p><h3>What is simulated here?</h3><p>The rates, latency, cost index, and risk values in this lab are deterministic educational metrics. They are not benchmark measurements from a live support agent, model, tool API, or human-review queue. The purpose is to make engineering cause and effect repeatable before a later Live Mode compares a policy against real executions.</p><h3>Common questions</h3>{faq([('Should I always lower max steps?','No. Too few steps can prevent valid multi-tool tasks from completing. The goal is a bounded budget that matches task complexity.'),('Should every tool call have a retry?','No. Retries should depend on the failure class and whether repeating the action is safe and idempotent.'),('Does human approval make an agent reliable?','It reduces risk around selected actions, but it does not fix bad planning, weak validation, or runaway loops elsewhere.'),('Why show success and runaway risk separately?','A system can complete many tasks successfully and still be operationally dangerous if a meaningful minority of runs loop, overspend, or take unsafe actions.')])}<div class="references"><strong>AhaFrame simulation note</strong> · Reviewed {UPDATED}. Metrics are synthetic and pedagogical; validate policies with representative traces and evaluation sets before production decisions.</div></section>
    <section class="card next-band"><div><strong>You improved one agent control policy.</strong><div class="subtle">The next Production Lab will focus on evaluation: how to prove that a new RAG or agent configuration is actually better across a representative test set.</div></div><a class="btn primary" data-event="agent_reliability_paid_intent_click" href="/en/early-access/?intent=agent-reliability-production-labs">Get Production Labs →</a></section></div>'''
    (target/'index.html').write_text(page(title,desc,path,body,active='Lessons',schemas=[schema,breadcrumb([('AhaFrame','/en/'),('Production Labs','/en/#roadmap'),('Agent Reliability Lab',path)])],scripts='<script src="/assets/agent-reliability.js" defer></script>'),encoding='utf-8')
