from .foundation import build_challenge, concept_guide, lesson_header, lesson_source, next_band, quick_answer, sidebar, takeaways, write_lesson


def _build(locale):
    slug='context-window';d=lesson_source(locale,slug);labels=d['labels']
    context_body=f'''<div class="container">{lesson_header(slug,'▱',locale,d)}{quick_answer(d['quick'],locale)}<div class="lesson-grid"><div><section class="card interactive" data-context-copy='{__import__('json').dumps(d['strategyNotes'],ensure_ascii=False)}'><div class="panel-title"><span>{labels['usage']}</span><span class="context-usage">191,250 / 200,000 tokens</span></div><div class="context-bar"><span class="seg-system" style="width:12%"></span><span class="seg-convo" style="width:42%"></span><span class="seg-docs" style="width:28%"></span><span class="seg-tools" style="width:12%"></span><span class="seg-memory" style="width:6%"></span></div><div class="subtle">{labels['composition']}</div><div class="demo-subtitle">{labels['choose']}</div><div class="strategy-row"><button type="button" class="strategy" data-strategy="drop">{labels['drop']}</button><button type="button" class="strategy active" data-strategy="summarize">{labels['summarize']}</button><button type="button" class="strategy" data-strategy="rag">{labels['rag']}</button><button type="button" class="strategy" data-strategy="memory">{labels['memory']}</button></div><div class="compare-grid"><div class="compare-card warn"><span class="label">{labels['before']}</span><strong>191,250 / 200,000</strong><div class="bar" style="margin-top:10px"><span style="width:96%;background:var(--warning)"></span></div><p class="subtle">{labels['beforeRisk']}</p></div><span class="flow-arrow">→</span><div class="compare-card good"><span class="label">{labels['after']}</span><strong><span data-after-count>112,430</span> / 200,000</strong><div class="bar" style="margin-top:10px"><span data-after-bar style="width:56%"></span></div><p class="subtle" data-after-note>{d['strategyNotes']['summarize']}</p></div></div><div class="note" style="margin-top:15px">{labels['principle']}</div></section>{takeaways(d['takeaways'],locale)}{build_challenge(d['challenge']['title'],d['challenge']['body'],locale)}</div><aside class="lesson-sidebar">{sidebar(d,locale,path_steps=d['path'])}</aside></div>{concept_guide(d,locale)}{next_band(d,locale)}</div>'''
    write_lesson(slug,locale,context_body,d,'<script src="/assets/context.js" defer></script>')


def build():
    for locale in ('en','zh-CN'):
        _build(locale)
