from textwrap import dedent

from .core import BASE, CONTENT, SITE, page


def build():
    h=CONTENT['home']
    item_list={'@context':'https://schema.org','@type':'ItemList','name':'AhaFrame interactive AI lessons and production labs','itemListElement':[]}
    for i,slug in enumerate(['token-playground','context-window','agent-loop'],1):
        d=CONTENT['lessons'][slug]
        item_list['itemListElement'].append({'@type':'ListItem','position':i,'url':f'{BASE}/en/lessons/{slug}/','item':{'@type':'LearningResource','name':d['name'],'description':d['description'],'url':f'{BASE}/en/lessons/{slug}/','publisher':{'@id':BASE+'/#organization'}}})
    lab_items=[
        ('RAG Failure Lab','Break and tune retrieval trade-offs across chunking, Top-K, reranking, context pressure, latency, and quality.','rag-failure'),
        ('Agent Reliability Lab','Tune retries, execution limits, validation, approval, termination, safety, latency, and cost.','agent-reliability'),
        ('Evaluation Failure Lab','Debug dataset coverage, slice regressions, evidence strength, safety vetoes, judge strategy, and release gates.','evaluation-failure'),
    ]
    for offset,(name,description,slug) in enumerate(lab_items,4):
        item_list['itemListElement'].append({'@type':'ListItem','position':offset,'url':f'{BASE}/en/labs/{slug}/','item':{'@type':'LearningResource','name':name,'description':description,'url':f'{BASE}/en/labs/{slug}/','publisher':{'@id':BASE+'/#organization'}}})
    home_schema=[{'@context':'https://schema.org','@type':'WebSite','@id':BASE+'/#website','name':'AhaFrame','url':BASE+'/en/','description':h['description'],'inLanguage':'en','publisher':{'@id':BASE+'/#organization'}},item_list]
    home_body=f'''
    <section class="hero"><div class="container hero-grid"><div><span class="eyebrow">Interactive AI Engineering</span><h1>Understand AI<br>by <span class="accent-text">seeing</span> it work.</h1><p class="lede">{h['subheadline']}</p><div class="actions"><a class="btn primary" data-event="hero_start_learning_click" href="/en/lessons/token-playground/">Start Learning →</a><a class="btn" data-event="hero_demo_click" href="#production-labs">Explore Production Labs</a></div><div class="proof-row"><span class="proof-chip">No signup required</span><span class="proof-chip">6 interactive experiences</span><span class="proof-chip">Simulation-first</span></div></div>
    <div class="card demo-card" aria-label="Interactive token playground preview"><div class="demo-header"><strong>Token Playground</strong><span class="live-badge">Interactive demo</span></div><div class="hero-demo-grid"><div class="hero-demo-main"><span class="label">Your prompt</span><div class="prompt-box">The capital of France is</div><div class="demo-subtitle">Next token prediction</div><div class="prob-row" data-hero-prob><span data-label>Paris</span><div class="bar"><span style="width:91%"></span></div><b data-value>91%</b></div><div class="prob-row" data-hero-prob><span data-label>Lyon</span><div class="bar light"><span style="width:3%"></span></div><b data-value>3%</b></div><div class="prob-row" data-hero-prob><span data-label>located</span><div class="bar light"><span style="width:2%"></span></div><b data-value>2%</b></div></div><aside class="hero-demo-side"><span class="label">Settings</span><div class="label" style="margin-top:14px">Temperature</div><div class="control-row"><input id="hero-temperature" class="slider" type="range" min="0" max="2" step="0.1" value="0.7" aria-label="Demo temperature"><output id="hero-temperature-value">0.7</output></div><div class="label" style="margin-top:21px">Sampling</div><select id="hero-sampling" class="select" aria-label="Sampling strategy"><option value="sample">Sample</option><option value="greedy">Greedy</option></select><div class="selected-panel"><span class="subtle">Example sampled token</span><div class="big" data-hero-selected>Paris</div></div></aside></div></div></div></section>
    <section class="section" id="lessons"><div class="container"><div class="section-head"><div><div class="section-kicker">Build the mental model</div><h2 class="section-title">Start with three interactive foundations</h2><p class="section-copy">Change a parameter, watch the system respond, and connect the result back to an engineering decision.</p></div><div class="card progress-card"><div class="progress-ring" data-progress-ring><strong data-progress-count>0/3</strong></div><div><h3>Your local progress</h3><p>Stored in this browser. No account needed.</p></div></div></div><div class="lesson-cards">
    <a class="card lesson-card" href="/en/lessons/token-playground/" data-event="lesson_card_click"><span class="lesson-status" data-lesson-status="token-playground">Not started</span><div class="lesson-num">01 · Foundations</div><div class="lesson-head"><div class="icon-box">◇</div><div><h3>Token Playground</h3><p>See how LLMs predict the next token.</p></div></div><div class="mini"><div class="prob-row"><span>Paris</span><div class="bar"><span style="width:91%"></span></div><b>91%</b></div><div class="prob-row"><span>Lyon</span><div class="bar light"><span style="width:16%"></span></div><b>3%</b></div><div class="prob-row"><span>located</span><div class="bar light"><span style="width:10%"></span></div><b>2%</b></div></div><span class="lesson-link">Try it now →</span></a>
    <a class="card lesson-card" href="/en/lessons/context-window/" data-event="lesson_card_click"><span class="lesson-status" data-lesson-status="context-window">Not started</span><div class="lesson-num">02 · Context Engineering</div><div class="lesson-head"><div class="icon-box warm">▱</div><div><h3>Context Window Lab</h3><p>See how context fills, overflows, and gets managed.</p></div></div><div class="mini"><div class="context-bar"><span class="seg-system" style="width:12%"></span><span class="seg-convo" style="width:42%"></span><span class="seg-docs" style="width:28%"></span><span class="seg-tools" style="width:12%"></span><span class="seg-memory" style="width:6%"></span></div><small class="subtle">191,250 / 200,000 tokens · almost full</small></div><span class="lesson-link">Try it now →</span></a>
    <a class="card lesson-card" href="/en/lessons/agent-loop/" data-event="lesson_card_click"><span class="lesson-status" data-lesson-status="agent-loop">Not started</span><div class="lesson-num">03 · Agents</div><div class="lesson-head"><div class="icon-box violet">⌘</div><div><h3>Agent Loop Simulator</h3><p>Step through act → observe → refine.</p></div></div><div class="mini flow-mini"><span class="flow-node">User</span><span class="flow-arrow">→</span><span class="flow-node">Agent</span><span class="flow-arrow">→</span><span class="flow-node">Tool</span><span class="flow-arrow">→</span><span class="flow-node">Observe</span></div><span class="lesson-link">Try it now →</span></a>
    </div></div></section>
    <section class="section" id="production-labs"><div class="container"><div class="section-head"><div><div class="section-kicker">Break systems on purpose</div><h2 class="section-title">Production Lab previews</h2><p class="section-copy">Start from a failure state. Tune the engineering policy, compare against the baseline, and learn what the system trades away when one metric improves.</p></div></div><div class="lesson-cards production-lab-grid" style="grid-template-columns:repeat(3,minmax(0,1fr))">
    <a class="card lesson-card" href="/en/labs/rag-failure/" data-event="production_lab_click"><span class="lesson-status">Available</span><div class="lesson-num">Production Lab · RAG</div><div class="lesson-head"><div class="icon-box warm">⌕</div><div><h3>RAG Failure Lab</h3><p>Fix retrieval without assuming more context is always better.</p></div></div><div class="mini"><div class="takeaway"><strong>Control</strong><span>Chunk size · Top-K · hybrid · reranker</span></div><div class="takeaway"><strong>Observe</strong><span>Recall · precision · context · quality · cost</span></div></div><span class="lesson-link">Break and tune RAG →</span></a>
    <a class="card lesson-card" href="/en/labs/agent-reliability/" data-event="production_lab_click"><span class="lesson-status">Available</span><div class="lesson-num">Production Lab · Agents</div><div class="lesson-head"><div class="icon-box violet">⌘</div><div><h3>Agent Reliability Lab</h3><p>Improve reliability without pretending retries, guardrails, and approvals are free.</p></div></div><div class="mini"><div class="takeaway"><strong>Control</strong><span>Steps · retries · timeout · validation · approval</span></div><div class="takeaway"><strong>Observe</strong><span>Success · runaway · safety · latency · cost</span></div></div><span class="lesson-link">Tune the agent policy →</span></a>
    <a class="card lesson-card" href="/en/labs/evaluation-failure/" data-event="production_lab_click"><span class="lesson-status">New</span><div class="lesson-num">Production Lab · Evaluation</div><div class="lesson-head"><div class="icon-box">✓</div><div><h3>Evaluation Failure Lab</h3><p>Find the release regression hidden behind a better aggregate score.</p></div></div><div class="mini"><div class="takeaway"><strong>Control</strong><span>Dataset · threshold · veto · samples · judge · cost</span></div><div class="takeaway"><strong>Decide</strong><span>SHIP · BLOCK · INCONCLUSIVE</span></div></div><span class="lesson-link">Debug the release decision →</span></a>
    </div></div></section>
    <section class="section"><div class="container"><div class="section-head"><div><div class="section-kicker">Learning model</div><h2 class="section-title">See. Play. Break. Aha. Build.</h2></div></div><div class="method-grid" style="grid-template-columns:repeat(5,minmax(0,1fr))"><div class="method"><span class="method-no">01</span><h3>See</h3><p>Make invisible AI states visible through clear diagrams and simulations.</p></div><div class="method"><span class="method-no">02</span><h3>Play</h3><p>Change parameters and compare outcomes instead of memorizing vocabulary.</p></div><div class="method"><span class="method-no">03</span><h3>Break</h3><p>Trigger failure modes intentionally so the weak assumptions become visible.</p></div><div class="method"><span class="method-no">04</span><h3>Aha</h3><p>Connect cause and effect until the system clicks as a durable mental model.</p></div><div class="method"><span class="method-no">05</span><h3>Build</h3><p>Apply the mental model to architecture, trade-offs, evaluation, and production decisions.</p></div></div></div></section>
    <section class="section" id="roadmap"><div class="container"><div class="section-head"><div><div class="section-kicker">AI engineering roadmap</div><h2 class="section-title">From foundations to production AI</h2><p class="section-copy">A curriculum designed around the systems developers actually need to understand and build.</p></div></div><div class="roadmap-shell"><div class="card roadmap">{''.join(f'<div class="roadmap-step"><span class="road-num">0{i}</span><strong>{name}</strong><small>{sub}</small></div>' for i,(name,sub) in enumerate([('Foundations','LLMs, tokens, embeddings'),('Context Engineering','Context, memory, chunking'),('RAG','Retrieval, indexing, reranking'),('Agents','Tools, planning, reliability'),('Evaluation','Quality, testing, observability'),('Production AI','Deploy, monitor, scale')],1))}</div><aside class="card audience-card" id="about"><h3>Built for builders and learners</h3><div class="audience-row"><span class="audience-icon">&lt;/&gt;</span><div><strong>Developers moving into AI</strong><br><span class="subtle">Translate software experience into AI-native engineering.</span></div></div><div class="audience-row"><span class="audience-icon">▣</span><div><strong>Product builders using LLMs</strong><br><span class="subtle">Understand the systems beneath the APIs.</span></div></div><div class="audience-row"><span class="audience-icon">◉</span><div><strong>Technical learners</strong><br><span class="subtle">Build intuition instead of memorizing vocabulary.</span></div></div></aside></div></div></section>
    <section><div class="container cta-band"><div><h2>Go from AI curiosity to AI engineering.</h2><p>Join early access for new failure simulations and production labs.</p></div><div><form class="signup" data-waitlist-form data-intent="homepage"><label class="sr-only" for="home-email">Email</label><input id="home-email" class="input" name="email" type="email" autocomplete="email" placeholder="Enter your email" required><button type="submit" class="btn primary">Join Early Access →</button></form><div data-status class="status"></div></div></div></section>
    '''
    home_body = dedent(home_body)
    (SITE/'en/index.html').write_text(page(h['title'],h['description'],'/en/',home_body,schemas=home_schema,scripts='<script src="/assets/home.js" defer></script>'),encoding='utf-8')
