from .core import BASE, SITE, UPDATED, breadcrumb, page, quick_answer


def opts(items):
    return ''.join(f'<option value="{value}">{label}</option>' for value,label in items)


def build():
    path='/en/build/reliable-support-agent/'
    target=SITE/'en/build/reliable-support-agent'
    target.mkdir(parents=True,exist_ok=True)
    title='Reliable Support Agent Build — Six-Layer Architecture Challenge | AhaFrame'
    desc='Combine Prompt, Context, Harness, Loop, Graph, and Evaluation decisions into one deterministic production architecture challenge.'
    groups=[
        ('prompt','Prompt', [('loose','Loose instruction contract'),('scoped','Scoped authority'),('typed','Typed prompt contract')]),
        ('retrieval','Retrieval', [('cheap','Cheap vector search'),('balanced','Balanced hybrid + rerank'),('recall','Recall-heavy hybrid')]),
        ('context','Context', [('lean','Lean context'),('balanced','Balanced protected context'),('rich','Rich context')]),
        ('execution','Harness + Loop', [('fast','Fast bounded loop'),('autonomous','Validated autonomous loop'),('bounded','Bounded + approval')]),
        ('graph','Graph', [('simple','Simple single-loop graph'),('bounded','Bounded branched graph'),('complex','Coordinator-heavy graph')]),
        ('evaluation','Evaluation', [('demo','Demo-biased evaluation'),('production','Production evaluation'),('safety','Safety-heavy evaluation')]),
    ]
    controls=''.join(f'<div><label class="label" for="build-{key}-policy">{label} policy</label><select id="build-{key}-policy" class="select">{opts(items)}</select></div>' for key,label,items in groups)
    metrics=''.join(f'<div class="metric">{label}<br><strong data-build-{key}>—</strong></div>' for key,label in [('architecture','Architecture score'),('task','Task readiness'),('reliability','Reliability'),('safety','Safety readiness'),('latency','Latency index'),('cost','Cost index')])
    paragraphs=[
        'The capstone changes the unit of reasoning from one subsystem to the whole AI system. A locally good choice can become a bad architecture when it conflicts with another layer. Strong retrieval cannot repair ambiguous instruction authority. A safe prompt cannot enforce a runtime permission boundary. A reliable loop can still live inside an unnecessarily complex graph. A good candidate can still be released under weak evidence.',
        'Prompt Engineering defines the behavioral contract: which instructions have authority, how consequential constraints are stated, how retrieved evidence is treated, and what output shape downstream systems can validate. In this challenge, unresolved Prompt conflicts are explicit blockers rather than a small quality penalty that can be averaged away.',
        'Context Engineering combines retrieval and working-context policy. Retrieval decides what evidence is available; compression decides what survives into the model working set. The architecture must retain enough critical information without exceeding the context budget or paying for evidence that does not improve the task.',
        'Harness and Loop Engineering control execution. Validation, approval, retries, timeouts, termination, and local recovery change reliability, operational cost, and risk. More retries can improve completion while making repeated work and long tails worse, so the execution policy must be judged as a production control system rather than a single success-rate number.',
        'Graph Engineering decides how responsibilities connect. A coordinator with many workers may look more advanced while increasing state coupling and failure propagation. A smaller branched workflow can preserve independent evidence, retry only the failed node, verify joins, and place review at the consequential boundary. The graph earns complexity only when that structure creates a measurable advantage.',
        'Evaluation Engineering turns all of those design choices into a release decision. Dataset coverage, evidence width, safety vetoes, and cost gates decide what counts as ready. The same architecture can look acceptable under a demo-biased evaluation and fail a production gate. This is why evaluation is part of system architecture rather than a final dashboard added after implementation.',
        'All values are deterministic educational abstractions composed from the existing AhaFrame Labs. They are not live model benchmarks or universal thresholds. The goal is to practice defending a coherent architecture under explicit constraints, then carry that reasoning into real systems with measured data.',
    ]
    explainer=''.join(f'<p>{text}</p>' for text in paragraphs)
    schema={'@context':'https://schema.org','@type':'LearningResource','name':'Reliable Support Agent Build','description':desc,'url':BASE+path,'inLanguage':'en','educationalLevel':'Intermediate to advanced','learningResourceType':'Interactive architecture challenge','timeRequired':'PT35M','isAccessibleForFree':True}
    body=f'''<div class="container"><div class="breadcrumb"><a href="/en/">Home</a> / Build / Reliable Support Agent</div><section class="lesson-hero"><div class="lesson-title-row"><div class="lesson-icon">⌘</div><div><h1>Reliable Support Agent Build</h1><div class="badges"><span class="badge level">Conceptual Closure Capstone</span><span class="badge">Six-layer architecture</span><span class="badge">35 min</span></div><p class="lede">Stop tuning components in isolation. Build one support system whose Prompt, Context, Harness, Loop, Graph, and Evaluation policies remain coherent together.</p></div></div><div class="lesson-tools"><button type="button" class="btn small" data-share>Share</button></div></section>{quick_answer('A production AI architecture is release-ready only when behavior, knowledge, runtime control, iteration, orchestration, and evaluation evidence agree with the same constraints.')}
    <div data-reliable-support-agent><section class="card interactive"><div class="panel-title"><span>Six-layer architecture</span><span class="badge">Deterministic integration challenge</span></div><div class="lab-control-grid" style="display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:20px">{controls}</div><div class="actions"><button type="button" class="btn primary" data-build-reference>Apply reference architecture</button><button type="button" class="btn" data-build-reset>Reset starting architecture</button></div><p class="subtle">The reference is one defensible configuration for this teaching scenario, not a universal answer key.</p></section>
    <section class="card lesson-section"><div class="panel-title"><span>Integrated stack</span><span class="badge" data-build-evidence>Evaluation evidence</span></div><div class="flow-mini" data-build-stack style="display:flex;gap:8px;flex-wrap:wrap;align-items:center"></div></section>
    <section class="card lesson-section"><div class="panel-title"><span>Release decision</span><strong class="badge" data-build-decision>—</strong></div><div class="metrics">{metrics}</div><div class="note"><strong>Diagnosis:</strong> <span data-build-diagnosis>—</span></div></section>
    <section class="roadmap-shell"><div class="card" style="padding:20px"><div class="panel-title">Release blockers</div><ul data-build-blockers class="takeaways"></ul></div><div class="card" style="padding:20px"><div class="panel-title">Trade-off warnings</div><ul data-build-warnings class="takeaways"></ul></div></section><section class="card lesson-section"><div class="panel-title">Architecture explanation</div><ul data-build-tradeoffs class="takeaways"></ul><div data-build-compare style="display:grid;gap:7px;margin-top:16px"></div></section></div>
    <section class="card section-explainer"><span class="eyebrow">BUILD · Conceptual Closure</span><h2>Defend the system, not one metric</h2>{explainer}</section><section class="card next-band"><div><strong>Conceptual closure means the six responsibilities now connect.</strong><div class="subtle">After this Build, AhaFrame stops adding content by default and moves to validation instrumentation and a small developer Alpha.</div></div><a class="btn primary" href="/en/early-access/?intent=validation-alpha">Join validation Alpha →</a></section></div>'''
    scripts='<script src="/assets/instruction-conflict-scenario.js" defer></script><script src="/assets/evaluation-scenario.js" defer></script><script src="/assets/context-compression-scenario.js" defer></script><script src="/assets/agent-workflow-graph-scenario.js" defer></script><script src="/assets/reliable-support-scenario.js" defer></script><script src="/assets/integrated-build.js" defer></script>'
    (target/'index.html').write_text(page(title,desc,path,body,active='Lessons',schemas=[schema,breadcrumb([('AhaFrame','/en/'),('Build','/en/#production-labs'),('Reliable Support Agent Build',path)])],scripts=scripts),encoding='utf-8')
