from .core import BASE, SITE, UPDATED, breadcrumb, faq, page, quick_answer, takeaways


def build():
    path='/en/labs/rag-failure/'
    title='RAG Failure Lab — Debug retrieval trade-offs | AhaFrame'
    desc='Break and tune a simulated RAG pipeline by changing chunk size, overlap, Top-K, retrieval strategy, and reranking while watching recall, precision, context usage, latency, and quality.'
    schema={
        '@context':'https://schema.org',
        '@graph':[
            {'@type':'WebPage','@id':BASE+path+'#webpage','url':BASE+path,'name':'RAG Failure Lab','description':desc,'inLanguage':'en','dateModified':UPDATED,'mainEntity':{'@id':BASE+path+'#learning-resource'}},
            {'@type':'LearningResource','@id':BASE+path+'#learning-resource','name':'RAG Failure Lab','description':desc,'url':BASE+path,'inLanguage':'en','educationalLevel':'Intermediate','learningResourceType':'Interactive simulation','timeRequired':'PT20M','isAccessibleForFree':True,'publisher':{'@id':BASE+'/#organization'}},
        ],
    }
    body=f'''<div class="container"><div class="breadcrumb"><a href="/en/">Home</a> / Production Labs / RAG Failure Lab</div><section class="lesson-hero"><div class="lesson-title-row"><div class="lesson-icon">⌕</div><div><h1>RAG Failure Lab</h1><div class="badges"><span class="badge level">Production Lab Preview</span><span class="badge">Intermediate</span><span class="badge">20 min</span></div><p class="lede">Start with a deliberately bad retrieval configuration. Change one engineering decision at a time and see why a RAG system can fail even when every component appears to be working.</p></div></div><div class="lesson-tools"><button type="button" class="btn small" data-share>Share</button></div></section>{quick_answer('RAG reliability is a trade-off between finding enough relevant evidence and keeping irrelevant or excessive context out of the model input.')}
    <div data-rag-lab><section class="card interactive"><div class="panel-title"><span>Broken production scenario</span><span class="badge">Deterministic simulation</span></div><p class="subtle">The starting configuration retrieves too many large chunks into a fixed 8,000-token context budget. Your job is to improve answer quality without treating “more context” as automatically better.</p><div style="display:grid;grid-template-columns:1fr 1fr;gap:24px;margin-top:18px"><div><label class="label" for="rag-chunk-size">Chunk size</label><div class="control-row"><input id="rag-chunk-size" class="slider" type="range" min="200" max="1400" step="100" value="1200"><output class="badge" data-rag-chunk-value>1200 tokens</output></div><label class="label" for="rag-overlap" style="display:block;margin-top:18px">Overlap</label><div class="control-row"><input id="rag-overlap" class="slider" type="range" min="0" max="1150" step="50" value="100"><output class="badge" data-rag-overlap-value>100 tokens</output></div><label class="label" for="rag-top-k" style="display:block;margin-top:18px">Top-K</label><div class="control-row"><input id="rag-top-k" class="slider" type="range" min="2" max="15" step="1" value="12"><output class="badge" data-rag-top-k-value>12</output></div></div><div><label class="label" for="rag-retrieval">Retrieval strategy</label><select id="rag-retrieval" class="select" style="margin-top:8px"><option value="vector">Vector only</option><option value="hybrid">Hybrid search</option></select><button type="button" class="btn wide" data-rag-reranker style="margin-top:16px">Reranker: OFF</button><div class="note" style="margin-top:16px"><strong>Fixed context budget:</strong> 8,000 tokens. This makes retrieval pressure visible instead of hiding the problem behind an ever-larger window.</div><div class="actions" style="margin-top:16px"><button type="button" class="btn primary" data-rag-balanced>Apply balanced preset</button><button type="button" class="btn" data-rag-reset>Reset failure baseline</button></div></div></div></section>
    <section class="card lesson-section" style="padding:20px;margin-top:18px"><div class="panel-title">What the system sees</div><div class="metrics" style="margin-top:14px"><div class="metric">Recall<br><strong data-rag-recall>—</strong></div><div class="metric">Precision<br><strong data-rag-precision>—</strong></div><div class="metric">Context<br><strong data-rag-context>—</strong></div><div class="metric">Quality score<br><strong data-rag-quality>—</strong></div><div class="metric">Latency<br><strong data-rag-latency>—</strong></div><div class="metric">Cost index<br><strong data-rag-cost>—</strong></div></div><div class="bar" style="margin-top:16px"><span data-rag-context-bar style="width:100%"></span></div><div class="note" style="margin-top:14px"><strong>Current diagnosis:</strong> <span data-rag-failure>Calculating…</span></div><div class="compare-grid" style="margin-top:16px"><div class="compare-card warn"><span class="label">Broken baseline</span><strong>Large chunks · Top-K 12 · vector only</strong><p class="subtle">Saved as an Engine checkpoint when the lab starts.</p></div><span class="flow-arrow">→</span><div class="compare-card good"><span class="label">Your current configuration</span><div data-rag-compare style="display:grid;gap:6px;margin-top:6px"><span>Waiting for changes…</span></div></div></div></section></div>
    {takeaways([('Recall is not enough','Retrieving more relevant evidence can still hurt if irrelevant context grows faster.'),('Top-K has a cost','Larger K increases coverage, but also context usage, latency, and retrieval noise.'),('Chunking changes the search surface','Very large chunks carry noise; very small chunks can fragment evidence.'),('Reranking is a precision tool','A reranker can recover precision after broader first-stage retrieval, but it adds latency and compute.')])}
    <section class="card section-explainer"><span class="eyebrow">Production mental model</span><h2>Why can a RAG system fail when retrieval “works”?</h2><p>A retrieval pipeline can successfully return documents and still produce a weak answer. The important question is not whether retrieval returned something; it is whether the model received the right evidence, with enough coverage and enough precision, inside a practical context budget.</p><h3>Chunk size is a representation decision</h3><p>Larger chunks can preserve surrounding context, but they also pull more unrelated text into each retrieval result. Smaller chunks are easier to match precisely, but can separate facts that need to be understood together. There is no universally correct chunk size, so production systems should evaluate it against representative queries.</p><h3>Top-K changes recall and noise at the same time</h3><p>Increasing Top-K often improves the chance that a relevant passage appears somewhere in the retrieved set. It also consumes more tokens and introduces more distractors. A system that only optimizes retrieval recall can therefore make the generation stage worse.</p><h3>Hybrid retrieval and reranking solve different problems</h3><p>Hybrid retrieval combines complementary first-stage signals such as semantic and lexical matching. Reranking is a second-stage precision step that reorders a candidate set using a stronger relevance model. They can work together, but each adds complexity and latency.</p><h3>What is simulated here?</h3><p>The scores in this lab are deterministic educational metrics, not benchmark results from a live embedding model, vector database, reranker, or LLM. The purpose is to make engineering cause-and-effect repeatable. A later Live Mode can compare these predicted trade-offs with real model behavior.</p><h3>Common questions</h3>{faq([('Should I always maximize recall?','No. Production answer quality depends on both evidence coverage and context precision.'),('Does a larger context window solve bad retrieval?','Not necessarily. More available tokens do not make irrelevant evidence useful.'),('Is hybrid search always better than vector search?','No. It is another retrieval strategy whose value depends on the data, queries, and evaluation set.'),('Why use a deterministic simulation first?','It lets learners change one variable at a time and observe repeatable causal effects before introducing model variance.')])}<div class="references"><strong>AhaFrame simulation note</strong> · Reviewed {UPDATED}. Metrics are synthetic and pedagogical; they should be validated against real datasets before production decisions.</div></section>
    <section class="card next-band"><div><strong>You fixed one RAG failure mode.</strong><div class="subtle">Next production labs will add evaluation sets, query-level failures, and eventually a Live Mode for real retrieval/model comparisons.</div></div><a class="btn primary" data-event="rag_paid_intent_click" href="/en/early-access/?intent=rag-production-labs">Get Production Labs →</a></section></div>'''
    (SITE/'en/labs/rag-failure/index.html').write_text(page(title,desc,path,body,active='Lessons',schemas=[schema,breadcrumb([('AhaFrame','/en/'),('Production Labs','/en/#roadmap'),('RAG Failure Lab',path)])],scripts='<script src="/assets/rag.js" defer></script>'),encoding='utf-8')
