from .foundation import build_challenge, concept_guide, lesson_header, lesson_source, next_band, quick_answer, sidebar, takeaways, write_lesson


def _build(locale):
    slug='token-playground';d=lesson_source(locale,slug);labels=d['labels']
    token_body=f'''<div class="container">{lesson_header(slug,'◇',locale,d)}{quick_answer(d['quick'],locale)}<div class="lesson-grid"><div><section class="card interactive"><div style="display:grid;grid-template-columns:1fr 1.3fr;gap:28px"><div><div class="panel-title">{labels['prompt']}</div><div class="task-box" style="margin-top:10px">The capital of France is</div></div><div><div class="panel-title">{labels['tokenization']}</div><div style="margin-top:10px"><span class="badge">The</span> <span class="badge">capital</span> <span class="badge">of</span> <span class="badge">France</span> <span class="badge">is</span></div></div></div><hr style="border:0;border-top:1px solid var(--line);margin:20px 0"><div style="display:grid;grid-template-columns:1.1fr 1fr;gap:28px"><div><div class="panel-title">{labels['probabilities']}</div><div class="prob-row" data-prob-row><span data-label>Paris</span><div class="bar"><span style="width:91%"></span></div><b data-value>0.91</b></div><div class="prob-row" data-prob-row><span data-label>Lyon</span><div class="bar light"><span style="width:3%"></span></div><b data-value>0.03</b></div><div class="prob-row" data-prob-row><span data-label>located</span><div class="bar light"><span style="width:2%"></span></div><b data-value>0.02</b></div></div><div><div class="panel-title">{labels['temperature']}</div><div class="temp-row" style="margin:15px 0"><input id="temperature" class="slider" type="range" min="0" max="2" value="0.7" step="0.05" aria-label="Temperature"><output id="temperature-value" class="badge">0.70</output></div><div class="selected-panel"><span class="subtle">{labels['sampled']}</span><div class="big" data-selected-token>Paris</div><span>{labels['probability']}: <b data-selected-prob>0.91</b></span></div></div></div></section>{takeaways(d['takeaways'],locale)}{build_challenge(d['challenge']['title'],d['challenge']['body'],locale)}</div><aside class="lesson-sidebar">{sidebar(d,locale,path_steps=d['path'])}</aside></div>{concept_guide(d,locale)}{next_band(d,locale)}</div>'''
    write_lesson(slug,locale,token_body,d,'<script src="/assets/token.js" defer></script>')


def build():
    for locale in ('en','zh-CN'):
        _build(locale)
