'use strict';
const assert=require('node:assert/strict');
const path=require('node:path');
const asset=(name)=>require(path.join(__dirname,'..','src','assets',name));
asset('lab-engine.js'); asset('lab-scenarios.js'); asset('instruction-conflict-scenario.js'); asset('evaluation-scenario.js'); asset('context-compression-scenario.js'); asset('agent-workflow-graph-scenario.js'); asset('reliable-support-scenario.js');
const AhaFrame=globalThis.AhaFrame;
const lab=AhaFrame.createLab('reliable-support-agent',{track:false});
let frame=lab.getFrame();
assert.equal(frame.state.promptPolicy,'loose');
assert.equal(frame.state.graphPolicy,'complex');
assert.equal(frame.state.evaluationPolicy,'demo');
assert.equal(frame.derived.decision,'BLOCK','starting architecture should expose cross-layer blockers');
assert.equal(frame.derived.diagnosisCode,'blocked');
assert.ok(frame.derived.blockers.some((item)=>item.includes('Prompt contract')));
assert.ok(frame.derived.blockers.some((item)=>item.includes('Graph failure propagation')));
assert.ok(frame.derived.blockerDetails.some((item)=>item.code==='prompt-conflicts'));
assert.ok(frame.derived.blockerDetails.some((item)=>item.code==='graph-propagation'));
assert.ok(frame.derived.warningDetails.some((item)=>item.code==='prompt-open'));
assert.ok(frame.derived.warningDetails.some((item)=>item.code==='demo-evaluation'));
assert.equal(frame.derived.labels.prompt,'Loose instruction contract');
assert.equal(frame.derived.labels.graph,'Coordinator-heavy graph');
lab.checkpoint('baseline');
frame=lab.dispatch('APPLY_REFERENCE_ARCHITECTURE');
assert.equal(frame.state.promptPolicy,'typed');
assert.equal(frame.state.retrievalPolicy,'balanced');
assert.equal(frame.state.contextPolicy,'balanced');
assert.equal(frame.state.executionPolicy,'bounded');
assert.equal(frame.state.graphPolicy,'bounded');
assert.equal(frame.state.evaluationPolicy,'production');
assert.equal(frame.derived.prompt.promptClosed,true);
assert.equal(frame.derived.graph.failureType,'healthy');
assert.equal(frame.derived.agent.failureType,'healthy');
assert.equal(frame.derived.context.failureType,'healthy');
assert.equal(frame.derived.decision,'SHIP','reference architecture should clear the modeled six-layer release gate');
assert.equal(frame.derived.diagnosisCode,'healthy');
assert.equal(frame.derived.blockers.length,0);
assert.equal(frame.derived.blockerDetails.length,0);
assert.ok(frame.derived.architectureScore>90);
assert.ok(frame.derived.safety>=95);
assert.ok(frame.derived.costIndex<75);
const diff=lab.compare('baseline');
assert.ok(diff.metrics.architectureScore.after>diff.metrics.architectureScore.before);
assert.ok(diff.metrics.reliability.after>diff.metrics.reliability.before);
assert.ok(diff.metrics.safety.after>diff.metrics.safety.before);
const promptOnly=AhaFrame.createLab('reliable-support-agent',{track:false});
promptOnly.dispatch('SET_PROMPT_POLICY',{value:'typed'});
assert.equal(promptOnly.getFrame().derived.decision,'BLOCK','fixing Prompt alone must not hide the bad Graph');
const graphOnly=AhaFrame.createLab('reliable-support-agent',{track:false});
graphOnly.dispatch('SET_GRAPH_POLICY',{value:'bounded'});
assert.equal(graphOnly.getFrame().derived.decision,'BLOCK','fixing Graph alone must not hide unresolved Prompt authority');
assert.throws(()=>lab.dispatch('SET_PROMPT_POLICY',{value:'magic'}),/Prompt policy must be one of/);
assert.throws(()=>lab.dispatch('SET_GRAPH_POLICY',{value:'mesh'}),/Graph policy must be one of/);
console.log('PASS Integrated Build: six-layer composition, semantic diagnostic codes, cross-layer blockers, reference architecture, checkpoint compare, and validation.');
