'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const text=fs.readFileSync(path.join(__dirname,'..','web','hooks','use-mission-runtime.ts'),'utf8');
assert.ok(text.includes('"prompt-injection-attack": "instruction_conflict_parameter_changed"'),'Prompt Injection Mission must preserve the stable instruction interaction event');
assert.ok(text.includes('const missionId = definition.runtimeId'),'Mission telemetry must use the canonical runtime missionId');
assert.ok(!text.includes('"mission_policy_changed"')&&!text.includes("'mission_policy_changed'"),'Prompt Injection Mission must not double-count with a second generic policy-change event');
for(const event of ['mission_started','simulation_run','release_decision_submitted','mission_completed'])assert.ok(text.includes(`"${event}"`),`missing ${event}`);
console.log('PASS Prompt Injection validation compatibility: stable interaction event + canonical Next Mission telemetry, no double emission.');
