create table if not exists public.validation_events (
  id bigint generated by default as identity primary key,
  event_id text not null unique,
  anonymous_user_id text not null,
  session_id text not null,
  name text not null,
  props jsonb not null default '{}'::jsonb,
  path text not null,
  event_ts timestamptz not null,
  page_type text not null default '',
  layer text not null default '',
  lab_id text not null default '',
  lab_version text not null default '',
  visit_count integer not null default 1 check (visit_count >= 1),
  return_visit boolean not null default false,
  utm_source text not null default '',
  utm_medium text not null default '',
  utm_campaign text not null default '',
  first_utm_source text not null default '',
  referrer text not null default '',
  device_class text not null default '',
  received_at timestamptz not null default now()
);

create index if not exists validation_events_name_ts_idx on public.validation_events (name, event_ts desc);
create index if not exists validation_events_lab_ts_idx on public.validation_events (lab_id, event_ts desc);
create index if not exists validation_events_anon_ts_idx on public.validation_events (anonymous_user_id, event_ts desc);
create index if not exists validation_events_session_idx on public.validation_events (session_id);

create table if not exists public.aha_feedback (
  id bigint generated by default as identity primary key,
  feedback_id text not null unique,
  anonymous_user_id text not null,
  session_id text not null,
  layer text not null default '',
  lab_id text not null,
  lab_version text not null default '',
  path text not null,
  rating text not null check (rating in ('no','little','yes','aha')),
  strong_aha boolean not null,
  note text not null default '' check (char_length(note) <= 1200),
  attribution jsonb not null default '{}'::jsonb,
  device_class text not null default '',
  submitted_at timestamptz not null,
  received_at timestamptz not null default now()
);

create index if not exists aha_feedback_lab_ts_idx on public.aha_feedback (lab_id, submitted_at desc);
create index if not exists aha_feedback_strong_idx on public.aha_feedback (strong_aha, submitted_at desc);

create table if not exists public.validation_waitlist (
  id bigint generated by default as identity primary key,
  email text not null unique,
  intent text not null default 'waitlist',
  source text not null default '',
  anonymous_user_id text not null default '',
  session_id text not null default '',
  layer text not null default '',
  lab_id text not null default '',
  lab_version text not null default '',
  utm_source text not null default '',
  utm_medium text not null default '',
  utm_campaign text not null default '',
  first_utm_source text not null default '',
  referrer text not null default '',
  device_class text not null default '',
  first_joined_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists validation_waitlist_intent_idx on public.validation_waitlist (intent, updated_at desc);

alter table public.validation_events enable row level security;
alter table public.aha_feedback enable row level security;
alter table public.validation_waitlist enable row level security;

revoke all on public.validation_events from anon, authenticated;
revoke all on public.aha_feedback from anon, authenticated;
revoke all on public.validation_waitlist from anon, authenticated;

grant select, insert, update on public.validation_events to service_role;
grant select, insert, update on public.aha_feedback to service_role;
grant select, insert, update on public.validation_waitlist to service_role;

grant usage, select on sequence public.validation_events_id_seq to service_role;
grant usage, select on sequence public.aha_feedback_id_seq to service_role;
grant usage, select on sequence public.validation_waitlist_id_seq to service_role;
