create table if not exists public.product_feedback (
  id bigint generated by default as identity primary key,
  product_feedback_id text not null unique,
  anonymous_user_id text not null,
  session_id text not null,
  cohort_id text not null default '',
  locale text not null default 'en',
  page_type text not null default '',
  layer text not null default '',
  lab_id text not null default '',
  lab_version text not null default '',
  feedback_type text not null check (feedback_type in ('bug','confusing','feature','other')),
  message text not null check (char_length(message) between 1 and 4000),
  email text not null default '' check (char_length(email) <= 320),
  path text not null default '',
  page_url text not null default '',
  device_class text not null default '',
  attribution jsonb not null default '{}'::jsonb,
  status text not null default 'new' check (status in ('new','triaged','planned','resolved','closed')),
  submitted_at timestamptz not null,
  received_at timestamptz not null default now()
);

create index if not exists product_feedback_status_ts_idx on public.product_feedback (status, submitted_at desc);
create index if not exists product_feedback_type_ts_idx on public.product_feedback (feedback_type, submitted_at desc);
create index if not exists product_feedback_lab_ts_idx on public.product_feedback (lab_id, submitted_at desc) where lab_id <> '';
create index if not exists product_feedback_cohort_ts_idx on public.product_feedback (cohort_id, submitted_at desc) where cohort_id <> '';

alter table public.product_feedback enable row level security;
revoke all on public.product_feedback from anon, authenticated;
grant select, insert, update on public.product_feedback to service_role;
grant usage, select on sequence public.product_feedback_id_seq to service_role;
